name: Cortar YouTube
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Link do YouTube'
        required: true
      inicio:
        description: 'Início HH:MM:SS'
        required: true
        default: '00:00:00'
      duracao:
        description: 'Duração HH:MM:SS' 
        required: true
        default: '00:00:30'
      nome:
        description: 'Nome do arquivo'
        required: false
        default: 'corte.mp4'

jobs:
  cortar:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Instalar yt-dlp e ffmpeg
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg
          python -m pip install -U yt-dlp

      - name: Baixar e cortar
        run: |
          yt-dlp "${{ github.event.inputs.url }}" \
          --download-sections "*${{ github.event.inputs.inicio }}-${{ github.event.inputs.inicio }}+${{ github.event.inputs.duracao }}" \
          --force-keyframes-at-cuts \
          -f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]/best" \
          --merge-output-format mp4 \
          --no-playlist \
          -o "${{ github.event.inputs.nome }}"
          
      - name: Upload do vídeo
        uses: actions/upload-artifact@v4
        with:
          name: corte-pronto
          path: ${{ github.event.inputs.nome }}
          retention-days: 2